Adjust link that was not functional anymore due to reorganization of …
cloudfoundry/cf-for-k8s-docs pull request #3
Opened 2021-06-09 06:58 UTC by benjaminguttmann-avtq

…pipeline files

The adjusted URL is not functional anymore due to the changes made in here => https://github.com/cloudfoundry/cf-for-k8s/commit/5c841b17895eb809316e43b8f07d795f7e0d0368#diff-21e072aa0ca4d97577a6d94c19ec3ae36ac8f49d0e5858f3b8c9a25892af7ae2

As there is no pipeline including all the steps from before I adjusted it to just point to the path in the repo including all the pipeline.yml files, otherwise I could image to make it point to the cf-for-k8s-main file. 

Please let me know if that is preferred from your side.

2021-06-29 10:00 UTC, benjaminguttmann-avtq commented
@Birdrock could you maybe have a look into this one please ?

2021-06-29 16:32 UTC, Birdrock requested changes

2021-06-29 16:32 UTC, Birdrock commented on content/docs/deploying/deploy-in-ci.md
> +You can see an example of how we combined these scripts in our own CI pipelines [here](https://github.com/cloudfoundry/cf-for-k8s/tree/main/ci/pipelines).
I believe the link should point to `https://github.com/cloudfoundry/cf-for-k8s/blob/main/ci/pipelines/cf-for-k8s-main.yml`. The intent was to provide our main pipeline definition.

2021-06-29 16:33 UTC, Birdrock commented
Hi @benjaminguttmann-avtq - thanks for opening the PR. I think the updated link should point to here: `https://github.com/cloudfoundry/cf-for-k8s/blob/main/ci/pipelines/cf-for-k8s-main.yml`

The link you provided is all the pipelines, and the intent was more to provide an example. I'm open to the argument that we should point to all of the pipelines if you think there is more value in providing all of them instead of a particular pipeline definition.

2021-06-30 06:14 UTC, benjaminguttmann-avtq commented
Hi @Birdrock,

thanks for your feedback.
I adjusted the URL accordingly. I can totally understand your comment, as I mentioned earlier I was not sure :) 
So now it is pointing to the `cf-for-k8s-main.yml`

Thx

2021-06-30 06:19 UTC, Birdrock approved these changes

2021-06-30 06:19 UTC, merged